### ISSUE TITLE
Python abend KeyError:'year'

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#118]
Input file:
year,mstat
 2023,2
Standard Error:

```
sas1 taxsim: python3.12 ../policyengine-taxsim/policyengine_taxsim/cli.py t.csv ;
Error processing input: 'year'
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/policyengine_taxsim/cli.py", line 48, in <module>
    main()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/policyengine_taxsim/cli.py", line 32, in main
    pe_situation = generate_household(taxsim_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/core/input_mapper.py", line 103, in generate_household
    year = str(int(taxsim_vars["year"]))  # Ensure year is an integer string
                   ~~~~~~~~~~~^^^^^^^^
KeyError: 'year'
```

I can't see what about "2023" isn't an integer. Does this happen on your machine? I wonder if my install is broken somehow.

**Comment by noman404** [comment]
@feenberg I tried to reproduce it on the current codebase from git, The provided input file failed on latest version for **taxsimid** 

```
 File "C:\Users\9520\PycharmProjects\policyengine-taxsim\policyengine_taxsim\core\output_mapper.py", line 33, in export_household
    taxsim_output["taxsimid"] = policyengine_situation.get("taxsimid", taxsim_input['taxsimid'])
                                                                       ~~~~~~~~~~~~^^^^^^^^^^^^
```

you can update the codebase by taking `git pull`

i'll be pushing a hotfix for it, but before that i need to know what are the minimum/required input variables for taxsim?

**Comment by feenberg** [comment]
I just updated the codebase with:

    `pip install policyengine_us --upgrade`

but I get the same error.  This was working 2 days ago on this machine.  The minimum variables required for taxsim are `mstat,year`. taxsimid is not required, nor are any of the dollar or age variables. Everything else has a default of zero. 

Please post actual instructions for installing the emulator on a new machine. I have a new machine with git and python3.12 and have no idea what to do after creating  directory `policyengine-taxsim`. It should be in the readme.txt anyway.

**Comment by noman404** [comment]
@feenberg this issue happens from policyengine-taxsim code, when you update policyengine_us it updates the dependency that used by policyengine-taxsim but not the codes of it. However, i'll be updating the readme into more step by step commands in details asap.

**Comment by feenberg** [comment]
I have updated everything - but can't get

    mstat,year
    2,2023

to work.

Can you send me the new install instructions without waiting for the 
README to be patched? I am pretty much dead in the water.

Just ran

    $ git pull
    Already up to date.

Then

    $ pip3.12 install policyengine_us --upgrade

<omit many "requirement already satisfied messages">

    Downloading policyengine_us-1.150.0-py3-none-any.whl (4.9 MB)
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq 4.9/4.9 MB 29.4 MB/s eta
    0:00:00
    Downloading policyengine_us_data-1.13.0-py3-none-any.whl (462 kB)
    qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq 462.5/462.5 kB 45.9 MB/s eta
    0:00:00
    Installing collected packages: policyengine-us-data, policyengine_us
    Successfully installed policyengine-us-data-1.13.0 policyengine_us-1.150.0

Then I tried to run cli.py:

    txmlinux: python3.12 cli.py txpydata.csv
    Traceback (most recent call last):
     File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py",
    line 5, in <module>
     from .core.input_mapper import generate_household
    ImportError: attempted relative import with no known parent package

    During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py",
     line 8, in <module>
     from policyengine_taxsim.core.input_mapper import generate_household
    ImportError: cannot import name 'generate_household' from
    'policyengine_taxsim.core.input_mapper'
     (/home/taxsim/.local/lib/python3.12/site-packages/policyengine_taxsim/core/input_mapper.py)


Daniel Feenberg

**Comment by feenberg** [comment]
I removed all of policyengine and followed the new instructions on the readme. Still no luck.
```
$ python3.12 cli.py txpydata.csv
Traceback (most recent call last):
  File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 5, in <module>
    from .core.input_mapper import generate_household
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 8, in <module>
    from policyengine_taxsim.core.input_mapper import generate_household
  File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/__init__.py", line 2, in <module>
    from .core.output_mapper import export_household
  File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/core/output_mapper.py", line 5, in <module>
    from policyengine_us import Simulation
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/policyengine_us/__init__.py", line 11, in <module>
    from policyengine_us.system import (
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/policyengine_us/system.py", line 2, in <module>
    from policyengine_core.taxbenefitsystems import TaxBenefitSystem
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/policyengine_core/__init__.py", line 1, in <module>
    from policyengine_core.simulations import Microsimulation, Simulation
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/policyengine_core/simulations/__init__.py", line 9, in <module>
    from .microsimulation import Microsimulation
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/policyengine_core/simulations/microsimulation.py", line 3, in <module>
    from microdf import MicroDataFrame, MicroSeries
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/microdf/__init__.py", line 51, in <module>
    from .taxcalc import (
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/microdf/taxcalc.py", line 2, in <module>
    from microdf._optional import import_optional_dependency
  File "/home/taxsim/policyengine-taxsim/venv/lib64/python3.12/site-packages/microdf/_optional.py", line 1, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
(venv) [taxsim@txmlinux policyengine_taxsim]$

```

**Comment by feenberg** [comment]
On Mon, 25 Nov 2024, Al Noman wrote:

> @feenberg Can you try on python 3.11

Sure:

    # python3.11 cli.py txpydata.csv
    Traceback (most recent call last):
      File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py",
      line 1, in <module>
     import click ModuleNotFoundError: No module named 'click'
     ***@***.*** policyengine_taxsim]# ls
     cli.py  core    __init__.py               __pycache__
     config  exe.py  policyengine_taxsim.spec  txpydata.csv
#

I see that "click" is a sophisticated command line interface. I question 
if the emulator needs such a thing. Given that there are no documented 
command line arguments, it might even be characterized as frivolous. 
Taxsim does not use any command line arguments, and reads and writes 
from/to standard in/out. That will be efficient and convenient for a 
combined emulator-taxsim function.

**Comment by noman404** [comment]
> On Mon, 25 Nov 2024, Al Noman wrote: @feenberg Can you try on python 3.11
> Sure: # python3.11 cli.py txpydata.csv Traceback (most recent call last): File "/home/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 1, in <module> import click ModuleNotFoundError: No module named 'click' ***@***.*** policyengine_taxsim]# ls cli.py core __init__.py __pycache__ config exe.py policyengine_taxsim.spec txpydata.csv # I see that "click" is a sophisticated command line interface. I question if the emulator needs such a thing. Given that there are no documented command line arguments, it might even be characterized as frivolous. Taxsim does not use any command line arguments, and reads and writes from/to standard in/out. That will be efficient and convenient for a combined emulator-taxsim function.
> […](#)
> -- Reply to this email directly or view it on GitHub: [#118 (comment)](https://github.com/PolicyEngine/policyengine-taxsim/issues/118#issuecomment-2498527255) You are receiving this because you were mentioned. Message ID: ***@***.***>

something definitely wrong during the installation, cause click already declared in the dependency and should be installed, can you please share the logs of the `pip install -e .`

```
dependencies = [
    "policyengine-us",
    "pandas",
    "PyYAML",
    "click",
    "matplotlib",
    "numpy"
]
```

**Comment by feenberg** [comment]
***@***.*** policyengine-taxsim]# pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be 
installed in editable mode: /home/taxsim/policyengine-taxsim
(A "pyproject.toml" file was found, but editable mode currently requires a 
setuptools-based build.)
