### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#125]
I updated today 

`pip3.12 install policyengine_us --upgrade`

[much omitted]

```
Successfully installed fsspec-2024.10.0 huggingface_hub-0.26.5 ipython-8.30.0 microdf-python-0.4.3 policyengine-core-3.15.0 policyengine-us-data-1.15.1 policyengine_us-1.160.0 psutil-6.1.0
WARNING: There was an error checking the latest version of pip.
```
but when I run 
```
sas1 taxsim: python3.11 ../txpydata.csv
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/../txpydata.csv", line 1, in <module>
    mstat,year
    ^^^^^
NameError: name 'mstat' is not defined
sas1 taxsim: python3.12 ../txpydata.csv
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/../txpydata.csv", line 1, in <module>
    mstat,year
    ^^^^^
NameError: name 'mstat' is not defined
```

either 3.11 or 3.12 I get the same error that mstat is not defined.

**Comment by feenberg** [comment]
As of 10 Dec 2024 the directions in the README worked, provided I substituted python3.12 for python and pip3.12 for pip. pip3.12 took about 20 minutes on our server.
