### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#141]
I just updated policyengine_us with:

`sas1 taxsim: pip3.12 install policyengin_us --upgrade`

and it seemed to work. but the output ended with this:
```
Successfully uninstalled policyengine-us-1.160.0
  WARNING: The script policyengine-us is installed in '/homes/nber/taxsim/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed policyengine_us-1.161.0
WARNING: There was an error checking the latest version of pip.

```
Then I tried to run the emulator and got this::

```
sas1 taxsim: python3.12 cli.py txpydata.csv
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 7, in <module>
    from .core.input_mapper import generate_household
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 10, in <module>
    from policyengine_taxsim.core.input_mapper import generate_household
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/__init__.py", line 2, in <module>
    from .core.output_mapper import export_household
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/core/output_mapper.py", line 6, in <module>
    from policyengine_tests_generator.core.generator import PETestsYAMLGenerator
ModuleNotFoundError: No module named 'policyengine_tests_generator'
```
I hope to work on this over the weekend - if you could suggest a fix I would appreciate it.

**Comment by PavelMakarchuk** [comment]
@noman404 could you take a look

**Comment by noman404** [comment]
Hi @feenberg , can you try it again be removing policyengine_taxsim package

`pip3.12 uninstall policyengine_taxsim`

then install again `pip3.12 install -e .`

**Comment by noman404** [comment]
Hi @feenberg , can you please try it again by removing policyengine_taxsim package

`pip3.12 uninstall policyengine_taxsim`

then install again `pip3.12 install -e .` 

i believe you have already taken a pull `git pull origin main` (meaning updated your codebase)

**Comment by feenberg** [comment]
Still no go:

```
sas1 taxsim: python3.12 cli.py ../txpydata.csv
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 7, in <module>
    from .core.input_mapper import generate_household
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/cli.py", line 10, in <module>
    from policyengine_taxsim.core.input_mapper import generate_household
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/__init__.py", line 2, in <module>
    from .core.output_mapper import export_household
  File "/disk/homedirs/nber/taxsim/policyengine-taxsim/policyengine_taxsim/core/output_mapper.py", line 6, in <module>
    from policyengine_tests_generator.core.generator import PETestsYAMLGenerator
ModuleNotFoundError: No module named 'policyengine_tests_generator'
```
Can we try to resolve this quickly?  I can do a screenshare anytime Monday from 6am on.

**Comment by feenberg** [comment]
Worked. Key was doing uninstall first.

**Comment by feenberg** [comment]
One problem - output.txt now begins with a blank line. That doesn't bother me, but it is non-standard and SAS proc import refuses to read the file.

**Comment by noman404** [comment]
> Worked. Key was doing uninstall first.

I'll add this as note in the Read me
