### ISSUE TITLE
ValueError: Variable ca_property_tax_credit does not exist.

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#28]
Using this input file:

```
sas1 taxsim: cat txpydata.csv
year,state,age1,age2,age3,depx,pwages,mstat,mortgage,taxsimid,idtl
2021,5,0,0,0,0,81000,1,0,1,2
```
Running with taxsim_emulator.py I get this error message:
```
sas1 taxsim: python3.12 ../policyengine-taxsim/taxsim_emulator.py txpydata.csv;
running script
Chosen Output Level: full
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 402, in <module>
    main(args.input_file)
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 390, in main
    output = make_dataframe(list_of_households, variable_dict, is_multiple_households(list_of_households))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 363, in make_dataframe
    output = [single_household(household, variable_dict)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 338, in single_household
    result = simulation.calculate(func,period=year)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/nber/taxsim/.local/lib/python3.12/site-packages/policyengine_core/simulations/simulation.py", line 460, in calculate
    result = self._calculate(variable_name, period)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/nber/taxsim/.local/lib/python3.12/site-packages/policyengine_core/simulations/simulation.py", line 585, in _calculate
    raise ValueError(f"Variable {variable_name} does not exist.")
ValueError: Variable ca_property_tax_credit does not exist.
sas1 taxsim:
```

**Comment by feenberg** [comment]
I get a similar result for Hawaii:
```
sas1 taxsim: cat txpydata.csv
year,state,age1,age2,age3,depx,pwages,mstat,mortgage,taxsimid,idtl
2021,12,0,0,0,0,81000,1,0,1,2
```
Maybe this affects evry state? (I also found a simlar error message from Kansas).

```
sas1 taxsim: sas petest
running script
Chosen Output Level: full
Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 402, in <module>
    main(args.input_file)
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 390, in main
    output = make_dataframe(list_of_households, variable_dict, is_multiple_households(list_of_households))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 363, in make_dataframe
    output = [single_household(household, variable_dict)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/taxsim_emulator.py", line 338, in single_household
    result = simulation.calculate(func,period=year)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/nber/taxsim/.local/lib/python3.12/site-packages/policyengine_core/simulations/simulation.py", line 460, in calculate
    result = self._calculate(variable_name, period)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/nber/taxsim/.local/lib/python3.12/site-packages/policyengine_core/simulations/simulation.py", line 585, in _calculate
    raise ValueError(f"Variable {variable_name} does not exist.")
ValueError: Variable hi_property_tax_credit does not exist.
output.csv: No such file or directory.
sas1 taxsim: ValueError: Varia
```

**Comment by PavelMakarchuk** [comment]
We currently only compute property tax credits for the following states:
Arizona
Connecticut 
Illinois 
Michigan
Missouri 
New Jersey
New York
Rhode Island
Wisconsin 
West Virginia 

There are issues filed to add the credits for the remaining states

**Comment by feenberg** [comment]
Is there a setting for the state variable that would allow me to test the 
federal calculation? Just a few weeks ago there were 8 functioning state
calculators. They may not have been 100% correct, but they let me do some 
testing of the federal calculator.

It is really undesirable to disable the entire calculation (including the 
federal tax) merely because a single feature is not yet implemented. It 
prevents me from comparing taxsim and policyengine for taxpayers not 
eligible for that feature. Since I start with a simple return, and will go 
on to more complex returns in the future, this would allow me to get 
started before the policyengine code is complete, which would be very 
desirable. I have some time now to work on this. That may not be true
in the future.

In general all the "placeholder" values should be plain numeric zeroes. 
On any IRS form, blanks are always zero, and never interfere with the 
calculation. We need to copy that.

We can talk about this in the morning.

Daniel Feenberg

**Comment by feenberg** [comment]
On Wed, 23 Oct 2024, Max Ghenis wrote:

> We're no longer getting this error using the Python package (it doesn't 
> return property tax credits). We will separately file issues to add more 
> variables like property tax credits iteratively.

Do I have accees to the Python package? How?

Daniel Feenberg

**Comment by noman404** [comment]
hi @feenberg if you take pull of main branch you'll have the latest package and to run the latest package you can command

python policyengine_taxsim\cli.py resources\taxsim35\taxsim_input.csv

the old taxsim_emulator.py is still there if you would like to use you can, by running the command with your input file (however we will be removing it in next PRs)

python taxsim_emulator.py taxsim_input.raw

**Comment by feenberg** [comment]
I was able to get some assistance with github here and have the new code, including cli.py. Using the command

   python3.12 policyengine_taxsim/cli.py <../petest/txpydata.csv

I get the message:

  Traceback (most recent call last):
  File "/disk/homedirs/nber/taxsim/petest/../policyengine-taxsim/policyengine_taxsim/cli.py",
  line 4, in <module>
    from policyengine_taxsim.core.input_mapper import
  import_single_household ModuleNotFoundError: No module named 'policyengine_taxsim'

I just did a "git clone" into an empty directory this morning, and have made no edits:

   sas1 taxsim: git status
   On branch main
   Your branch is up to date with 'origin/main'.
   nothing to commit, working tree clean

I note that the policyengine-taxsim directory and subdirectories
contain no file matching "policyengine_taxsim*"

Any ideas?
