### ISSUE TITLE
Installing in FreeBSD

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#89]
I am trying to install the emulator on a FreeBSD system with the pip command, but I need more information than is provided. This is on a server that has never had any PolicyEngine software on it before.

1) The readme tells me to "Open terminal in the parent directory", but doesn't say what directory that is. I tried making the parent "/home/feenberg/policyengine-taxsim" and ran:
```
feenberg@taxsimssh:~ % pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///usr/home/feenberg
ERROR: file:///usr/home/feenberg does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
I also tried spelling out "policyengine-taxsim" instead of ".". No help.

2) Next I tried the direct method:

```
root@taxsimssh:/etc/ssh # pip install git+https://github.com/PolicyEngine/policyengine-taxsim.git
Collecting git+https://github.com/PolicyEngine/policyengine-taxsim.git
  Cloning https://github.com/PolicyEngine/policyengine-taxsim.git to /tmp/pip-req-build-7um8pc8h
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

Does the pip install also require git?

**Comment by feenberg** [comment]
Moving back to Linux with a newly installed OS, I was able to clone the repository, but the pip step failed. See the last four lines below for the error message.:


```
[taxsim@txmlinux ~]$ git clone "https://github.com/PolicyEngine/policyengine-taxsim"
Cloning into 'policyengine-taxsim'...
remote: Enumerating objects: 350, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 350 (delta 104), reused 177 (delta 92), pack-reused 134 (from 1)
Receiving objects: 100% (350/350), 2.24 MiB | 7.71 MiB/s, done.
Resolving deltas: 100% (135/135), done.
[taxsim@txmlinux ~]$ ls -ltr
total 2328
-rwxr-xr-x. 1 taxsim taxsim 2376376 Nov  6 16:46 linux
drwxr-xr-x. 7 taxsim taxsim    4096 Nov 10 11:17 policyengine-taxsim
[taxsim@txmlinux ~]$ cd policyengine-taxsim
[taxsim@txmlinux policyengine-taxsim]$ git pull
Already up to date.
[taxsim@txmlinux policyengine-taxsim]$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/taxsim/policyengine-taxsim
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
However, there is a cli.py program so I tried it in spite of the message above: 
```
[taxsim@txmlinux tests]$ python ../policyengine_taxsim/cli.py test_e2e.py
Traceback (most recent call last):
  File "/home/taxsim/policyengine-taxsim/tests/../policyengine_taxsim/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
[taxsim@txmlinux tests]$ pwd
/home/taxsim/policyengine-taxsim/tests
```
Next step?

**Comment by feenberg** [comment]
Realized that Redhat linux comes with Python3.9. I was able to install 3.12 got a different result:

```
cli.py  linux  policyengine-taxsim  test_e2e.py  test_mappers.py
[taxsim@txmlinux ~]$ python3.12 cli.py test_e2e.py
Error processing input: Error tokenizing data. C error: Expected 1 fields in line 25, saw 2

Traceback (most recent call last):
  File "/home/taxsim/cli.py", line 48, in <module>
    main()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/taxsim/cli.py", line 26, in main
    df = pd.read_csv(input_file)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 25, saw 2

[taxsim@txmlinux ~]$
```
